line:
  bot:
    channel-secret: Your secret
    channel-token: Your token
    channel-token-supply-mode: fixed
    connect-timeout: 60000
    handler:
      enabled: true
      path: /callback
    read-timeout: 60000
    write-timeout: 60000

openai:
  token: Your token
  model: gpt-3.5-turbo
